### ISSUE TITLE
Setup project with Firebase, Remix and GraphQL to build the blog

### ISSUE THREAD

**Issue by fahadahmed** [fahadahmed/roadmap-personal#1]
# Overview
Setup the project to build a blog with admin section using Firebase, Remix and GraphQL API deployed to Firebase Functions.

## Tasks
- [x] Setup Remix web app
- [x] Setup Firebase services to talk to Remix app (Auth, Firestore and Functions)
- [x] Setup Firebase Functions to serve a GraphQL API server

## Additional context
[Remix](https://remix.run/)
[Deploying GraphQL Server on Firebase Functions](https://brygrill.medium.com/deploying-a-graphql-server-with-cloud-functions-for-firebase-6aa5dec2c8bc)
[Deploying Apollo Server on Firebase Functions](https://www.tirupatibalan.com/2020/04/23/firebase-graphql-apollo.html)
