### ISSUE TITLE
Code Formatting: Setup Eslint, Prettier and Husky

### ISSUE THREAD

**Issue by fahadahmed** [fahadahmed/roadmap-personal#10]
# Overview
Set up code formatting tools like Eslint, Prettier and Husky for the project

## Tasks
- [x] Setup Eslint for `app` and `functions` folders
- [x] Setup Prettier for `app` and `functions` folders
- [ ] Setup Lint-staged and Husky for pre-commit hook
