### ISSUE TITLE
Setup Firebase Emulators for local development

### ISSUE THREAD

**Issue by fahadahmed** [fahadahmed/roadmap-personal#13]
# Overview
Setup Firebase Emulators for local app development

## Tasks
- [ ] Setup Firebase Auth Emulator
- [ ] Setup Firestore Emulator
- [ ] Setup Firebase Functions to work locally through Emulator

## Additional context
- [Firebase Emulator Suite](https://firebase.google.com/docs/emulator-suite)

**Comment by fahadahmed** [comment]
Setup Firebase Auth Emulator with login/sign-in with email and password. Implement a workflow that presents a login page and authenticates the user via the emulator when running the NextJS app in `dev` mode and connects to the production auth when app is deployed to Firebase Hosting.
- [ ] update the README  file with the required documentation
