### ISSUE TITLE
Issues Section

### ISSUE THREAD

**Issue by fahadahmed** [fahadahmed/roadmap-personal#16]
# Overview
Implement the `Issues` section in the admin app.

## Tasks
- [x] Implement the view where all the Issues are listed
- [x] Implement the view to create a new issue with an `unpublished` state
- [ ] Implement the view to edit details of an `unpublished` state
- [ ] Implement the action to publish an issue (to be done possibly later)

## References
Issues are a collection of posts (articles) that are published at the same time so that viewers can enjoy content in a magazine like feature. Hence CRUD operations in traditional way are not possible.
- An Issue can contain `n` number of posts.
- Each post needs to be published for the Issue to be published
- Once the issue is published, it cannot be deleted. It can be archived.
- When an issue is archived, all the posts in that issue will also be archived automatically.
