### ISSUE TITLE
Posts Section

### ISSUE THREAD

**Issue by fahadahmed** [fahadahmed/roadmap-personal#17]
# Overview
Implement the `Posts` section in the admin app.

## Tasks
- [x] Implement the view where all the Posts are listed. They can be listed in a tabular format to show title and tags as well as status of the post.
- [x] Implement the view to create a new post with an `unpublished` state. It should include the following properties: `title`, `slug`, `excerpt`, `content` and a list of `tags`.
- [x] Implement the view to edit details of a post
- [ ] Implement the action to publish an post (to be done possibly later)

## References
TBA
