### ISSUE TITLE
Project Scaffold - Setup

### ISSUE THREAD

**Issue by fahadahmed** [fahadahmed/roadmap-personal#26]
# Overview
Setup the project repository @fahadahmed/fhdamd for the development of the personal blog using latest web technologies

## Tasks
- [x] Setup nx
- [x] Setup Remix web app
- [x] Setup Strapi as backend app
- [x] Setup components library
- [ ] Setup GraphQL and Apollo client in web app
- [ ] Setup Web app to read data from Strapi
- [ ] Setup Deployment to Fly.io
- [ ] Setup Postgres SQL and connect to Strapi instance on Fly.io
- [ ] Setup Github actions
- [x] Setup Vitest for testing
- [ ] Setup Cypress for E2E testing
- [ ] Setup Eslint, Prettier and Husky for code formatting
- [ ] Setup Firebase Functions
- [ ] Setup Firebase Analytics
- [ ] Setup Performance Monitoring
