### ISSUE TITLE
Documentation - update README file

### ISSUE THREAD

**Issue by fahadahmed** [fahadahmed/roadmap-personal#5]
# Overview
Update the readme file with the steps to develop and deploy the solution to Firebase and Fly.io

## Tasks
- [ ] update steps to start Firebase Emulators to allow local development
- [ ] update steps to start web app in dev mode
- [ ] update steps to deploy the solution using GitHub actions

## Additional context
TBA
