### ISSUE TITLE
Implement an admin section for the app

### ISSUE THREAD

**Issue by fahadahmed** [fahadahmed/roadmap-personal#6]
# Overview
Implement an admin section for the app that allows CRUD for the app

## Tasks
- [ ] CRUD for Issues
- [ ] CRUD for Tags
- [ ] CRUD for Posts
- [ ] Integrate Firebase Authentication

## Additional context
Proper relationships should exist between Issues, Posts and Tags.

**Comment by fahadahmed** [comment]
Need to rework the app setup based on just Remix and Firebase without Graphql first
