### ISSUE TITLE
Setup repo with Remix and Firebase

### ISSUE THREAD

**Issue by fahadahmed** [fahadahmed/roadmap-personal#7]
# Overview
Setup the repo again with Remix and Firebase. 

## Tasks
- [x] Setup a simple minimal config Remix app
- [ ] Setup Firebase Authentication to access the apps admin area
- [ ] Setup Firestore to be used as database
- [ ] Setup Firebase Emulators
- [ ] Setup Apollo GraphQL client to connect to the backend
